### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by APratham** [chriskyfung/qwiklabs-completed-labs-tracker#25]
The userscript doesn't work now, please let me know if something is broken or I am doing it wrong

**Comment by chriskyfung** [comment]
The script works well.

Could you please provide the debug logs?

**Comment by chriskyfung** [comment]
## Features that are still working

🆗 Show ✔ on lab pages
🆗 Annotate the items on `/catalog` pages

## Features failed after major UI update

❌ Show ✔ on quest pages
❌ Annotate the items on Home page
❌ Annotate and record the items in the Activities tab on Profile page

### 🚧 Fix progress...

[ ] Show ✔ on quest pages
[ ] Annotate the items on Home page
[ ] Annotate the items in the Activities tab on Profile page
[ ] Record the items in the Activities tab on Profile page
