### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by jpnaquet** [chriskyfung/qwiklabs-completed-labs-tracker#5]
Your tool is great as it is a real mess to follow what you have done in Qwiklabs. Unfortunately, I followed your instructions but it is not working for me. No checkmark next to my labs.

![Qwiklabs](https://user-images.githubusercontent.com/65893090/82795969-10e49700-9e75-11ea-8be2-102e92b3d244.png)

**Comment by chriskyfung** [comment]
Thanks for your message.

The current version still requires manually mark each lab status inside the script.

Add `finished` as the value of `status` in the latest version.

**Comment by jpnaquet** [comment]
Thanks Chris. It is working like you said. Adding the `finished` tag will do the trick. It will be easier to have a local file with the achieved quests and labs. What do you think ?

**Comment by chriskyfung** [comment]
I recommend you update to v0.5.1.

**Comment by chriskyfung** [comment]
> Thanks Chris. It is working like you said. Adding the `finished` tag will do the trick. It will be easier to have a local file with the achieved quests and labs. What do you think ?

I recommend you update to v0.5.1.
